name: Release
on: 
  workflow_dispatch:
    inputs:
      semver:
        description: 'Semantic Version Bump'     
        required: true
        default: 'prerelease' 
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease

jobs:
  publish:
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SEMVER: ${{ github.event.inputs.semver }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lacedltd'
      - run: npm version $SEMVER --preid=ci-$GITHUB_RUN_ID
      - run: npm run package
      - run: npm publish $(ls *.tgz)
      - name: Push changes
        if: ${{ env.SEMVER != 'prerelease' }}
        run: git push
